const MODEL='https://justadudewhohacks.github.io/face-api.js/models', E={neutral:'Neutral',happy:'Happy',sad:'Sad',angry:'Angry',fearful:'Fearful',disgusted:'Disgusted',surprised:'Surprised'};let ready=false,stream=null,run=false,file=null;
const $=x=>document.getElementById(x),toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)},hist=()=>JSON.parse(localStorage.getItem('emotionHistory')||'[]'),save=h=>localStorage.setItem('emotionHistory',JSON.stringify(h.slice(0,100)));
async function models(){try{await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(MODEL),faceapi.nets.faceExpressionNet.loadFromUri(MODEL)]);ready=true;$('status').textContent='Model ready';$('dot').className='ready';$('liveStatus').textContent='AI model ready';toast('AI model ready')}catch(e){$('status').textContent='Model failed';$('liveStatus').textContent='Model failed - check internet';toast('Model could not load. Check internet.')}}
function stats(){let h=hist(),c={};h.forEach(x=>c[x.emotion]=(c[x.emotion]||0)+1);$('sessions').textContent=h.length;$('faces').textContent=h.reduce((a,x)=>a+x.faces,0);$('top').textContent=h.length?Object.entries(c).sort((a,b)=>b[1]-a[1])[0][0]:'—';$('recent').innerHTML=h.slice(0,5).map(x=>`<div class="history-row"><span>${new Date(x.time).toLocaleString()}</span><b>${x.emotion} · ${Math.round(x.conf*100)}%</b></div>`).join('')||'No detections yet.';$('tbody').innerHTML=h.map(x=>`<tr><td>${new Date(x.time).toLocaleString()}</td><td>${x.source}</td><td>${x.faces}</td><td>${x.emotion}</td><td>${Math.round(x.conf*100)}%</td></tr>`).join('')||'<tr><td colspan="5">No history.</td></tr>'}
function add(source,rs){if(!rs.length)return;let e=rs.slice().sort((a,b)=>b.conf-a.conf)[0],h=hist();h.unshift({time:new Date().toISOString(),source,faces:rs.length,emotion:e.emotion,conf:e.conf});save(h);stats()}
function bars(ex){return ex.asSortedArray().map(x=>`<div class="emotion"><div class="label"><span>${E[x.expression]}</span><b>${Math.round(x.probability*100)}%</b></div><div class="bar"><i style="width:${x.probability*100}%"></i></div></div>`).join('')}
function switchPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('show'));$(id).classList.add('show');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('title').textContent={dashboard:'Emotion Dashboard',live:'Live Detection',upload:'Image Analysis',history:'Detection History',about:'About Project'}[id];scrollTo(0,0)}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>switchPage(x.dataset.page));
$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.dark=document.body.classList.contains('dark')};if(localStorage.dark==='true')document.body.classList.add('dark');
async function start(){if(!ready)return toast('Wait for the AI model to load.');try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('video').srcObject=stream;$('placeholder').style.display='none';run=true;loop();toast('Camera started')}catch(e){toast('Camera permission denied or unavailable.')}}function stop(){run=false;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('placeholder').style.display='grid';$('liveResults').textContent='No face detected.'}
async function loop(){if(!run)return;let v=$('video');if(v.readyState>1)try{let r=await faceapi.detectAllFaces(v,new faceapi.TinyFaceDetectorOptions({inputSize:416,minConfidence:.45})).withFaceExpressions(),c=$('canvas');c.width=v.clientWidth;c.height=v.clientHeight;let ctx=c.getContext('2d'),sx=v.clientWidth/v.videoWidth,sy=v.clientHeight/v.videoHeight;ctx.clearRect(0,0,c.width,c.height);r.forEach(x=>{let b=x.detection.box,e=x.expressions.asSortedArray()[0];ctx.strokeStyle='#8b68ff';ctx.lineWidth=3;ctx.strokeRect(b.x*sx,b.y*sy,b.width*sx,b.height*sy);ctx.fillStyle='#111a';ctx.fillRect(b.x*sx,b.y*sy,130,25);ctx.fillStyle='#fff';ctx.font='12px Arial';ctx.fillText(`${E[e.expression]} ${Math.round(e.probability*100)}%`,b.x*sx+5,b.y*sy+17)});$('liveResults').innerHTML=r.length?r.map((x,i)=>`<h4>Face ${i+1}</h4>${bars(x.expressions)}`).join(''):'No face detected.'}catch(e){}requestAnimationFrame(loop)}
$('start').onclick=start;$('stop').onclick=stop;$('capture').onclick=()=>{if(!stream)return toast('Start camera first');let c=document.createElement('canvas'),v=$('video');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(b=>{let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='emotion-capture.png';a.click()})};
$('file').onchange=e=>{file=e.target.files[0];if(!file)return;$('preview').src=URL.createObjectURL(file);$('preview').style.display='block';$('analyze').disabled=false};$('analyze').onclick=async()=>{if(!ready||!file)return;let img=await faceapi.bufferToImage(file),r=await faceapi.detectAllFaces(img,new faceapi.TinyFaceDetectorOptions({inputSize:416,minConfidence:.4})).withFaceExpressions();$('imageResults').innerHTML=r.length?r.map((x,i)=>`<h4>Face ${i+1}</h4>${bars(x.expressions)}`).join(''):'No face detected.';if(r.length){add('Uploaded image',r.map(x=>{let e=x.expressions.asSortedArray()[0];return{emotion:E[e.expression],conf:e.probability}}));toast(`${r.length} face(s) analyzed`)}};
$('clear').onclick=()=>{if(confirm('Clear all history?')){save([]);stats();toast('History cleared')}};stats();window.addEventListener('beforeunload',stop);models();
